quick-start.md
Some small visual changes and improved example code, to make it more beginner friendly.
=> V1.0.0 beta

SUMMARY.md, glossary.md
The start of a glossary section.
=> Added glossary section

quick-start/dapps/react-native.md
From (asyncStorage AsyncStorage) to (asyncStorage: AsyncStorage)
=> Typo in storageOptions

docs/quick-start/wallets/react-native.md
=> Update React Native documentation

docs/mobile-linking.md, versioned_docs/version-1.0/mobile-linking.md
=> update registry links on mobile registry

docs/api/registry-api.md
Closes https://github.com/WalletConnect-Inc/cloud-app/issues/91
=> docs: adds documentation for v1 of registry API

docs/api/registry-api.md
- Add new params for search and pagination
- Update return examples
cc @chadyj 
https://walletconnect-docs-git-registry-api-docs-walletconnect1.vercel.app/2.0/api/registry-api#listings-api
=> Update listings api documentation

docs/quick-start/dapps/ethereum-provider.md
Relevant page: https://walletconnect-docs-git-docs-ethereum-provider-walletconnect1.vercel.app/2.0/quick-start/dapps/ethereum-provider
=> Adds docs for v2 EthereumProvider

versioned_docs/version-1.0/mobile-linking.md
Double negation. I think this is the actual meaning.
=> Should not be considered valid

docs/README.md, versioned_docs/version-1.0/README.md
Closes https://github.com/WalletConnect/walletconnect-docs/issues/153
=> Fix broken link

vercel.json
closes https://github.com/WalletConnect/walletconnect-docs/issues/152#issuecomment-1050701373
=> Add vercel.json with redirects

README.md, versioned_docs/version-1.0/README.md
Summary:
- [Improve: adding table and split to two column](https://github.com/WalletConnect/walletconnect-docs/pull/163/commits/94e077da356c014320ebf85f821df1aaf50e63a0)[](https://github.com/BaseMax)
- [set community name as BOLD](https://github.com/WalletConnect/walletconnect-docs/pull/163/commits/27203c002c01d7597990649e91c9de3938aa2e82)[](https://github.com/BaseMax)
- [Improve: change Github to GitHub](https://github.com/WalletConnect/walletconnect-docs/pull/163/commits/6d42ff752346a5aa8e9bd7d01ee9ef4c45df2237)[](https://github.com/BaseMax)
- [Improve version1.0 readme: add . and : after lines](https://github.com/WalletConnect/walletconnect-docs/pull/163/commits/e5db941e9dbfa5becf355caba0b44eb312d02836)[](https://github.com/BaseMax)
- [set QR Code as …
=> Improve version1.0 document

docs/introduction/examples-and-resources.md, sidebars.js
- Collapsed sidebar categories to make things easier to glance
- Updated web examples
=> Improve sidebar readability

versioned_docs/version-1.0/cloud-registry.md, versioned_sidebars/version-1.0-sidebars.json
I've noticed devs in the Discord and Issues, having a hard time finding documentation on submitting their projects to the Registry. So I decided to add Pedro's blogpost to the sidebar for a simple fix.
=> Add @pedrouid 's Cloud Registry article in the docs

docs/about.md, docs/introduction/auth.md, docs/introduction/chat.md, docs/introduction/push.md, docs/javascript/sign/wallet-usage.md
Just added a bit more information on about page and added introductions for all the 4 SDKs
=> More descriptive about page and SDK introduction pages

docs/javascript/sign/wallet-usage.md
Follow-up to: https://github.com/WalletConnect/walletconnect-docs/pull/197
@hackyguru only saw your PR above once it was already merged, otherwise would've added these tweaks as part of review :)
- Noticed a broken link and some mentions of dapp where it should be wallet. 
- Also tried to expand the code snippets some more based on the original migration guide here:
https://gist.github.com/pedrouid/1a36c6a8776e49453838578ec84715e6#biggest-changes-introduced-in-beta-100-include
I think we can still iterate both the wallet and dapp usage guides more and make them more useful before v2 hits release candidate. Something to discuss in Thailand together 👍
=> docs(wallet-usage): fix broken link, expand on code snippets

docs/swift/sign/wallet-usage.md
Added WebSocketFactory implementation example using Starscream v3
=> SocketFactory instructions

docs/javascript/sign/dapp-usage-standalone-client.md, docs/javascript/sign/wallet-usage.md
added code sandbox examples for wallet and dapp side in the js sign sdk.
=> adding codesandbox embeds for js sign

docusaurus.config.js
Deafult to dark theme to match the new look.
=> default to dark theme

docs/introduction/cloud.md, docs/introduction/registry.md, sidebars.js
Reverts WalletConnect/walletconnect-docs#221
=> Revert "Renaming Registry to Cloud Explorer"

docs/introduction/cloud-explorer.md, docs/introduction/cloud.md, sidebars.js
Reverts WalletConnect/walletconnect-docs#226
=> Rename registry to cloud explorer

docs/introduction/examples-and-resources.md
Added repo link to dapp and wallet examples for Swift
=> Adding sample apps for swift

docs/javascript/sign/wallet-usage.md, package.json, yarn.lock
* Update dependencies
* Add event interfaces to wallet usage page
* Format wallet usage page
=> JS Sign client doc additions, dependency updates

docs/swift/relay/relay-setup.md, docs/swift/sign/dapp-usage.md, docs/swift/sign/wallet-usage.md
Relay client separated to singleton. Before Sign SDK usage necessary to configure shared Relay instance
=> Relay Client configuration

docs/javascript/auth/dapp-usage.md, docs/javascript/auth/installation.md, docs/javascript/auth/wallet-usage.md, sidebars.js
- Update installation.md with actual auth installation instructions
- Add initial dapp usage and wallet usage docs
=> Add initial Auth SDK docs

docs/swift/auth/app-usage.md, docs/swift/auth/wallet-usage.md, docs/swift/relay/usage.md, docs/swift/sign/dapp-usage.md, docs/swift/sign/wallet-usage.md
- update Sign dApp usage - close #204
- fix relay usage reference in sign and auth
- update relay usage
=> Update swift docs

docusaurus.config.js
Add an announcement bar that helps developers get started with the correct version.
=> Add version announcement bar

versioned_docs/version-1.0/quick-start/dapps/react-native.md
If you don't add these queries.intent in AndroidManifest, the Linking.canOpenUrl(uri) will always return false. This is critical point
=> Update react-native.md | Android 29^ compatibility

docs/kotlin/auth/dapp-or-requester-usage.md, docs/kotlin/auth/installation.md, docs/kotlin/auth/wallet-or-responder-usage.md, sidebars.js
Closes [Kotlin #403](https://github.com/WalletConnect/WalletConnectKotlinV2/issues/403)
=> docs: Add Kotlin Auth SDK docs

docs/kotlin/guides/mobile-linking.md, docs/kotlin/guides/relay.md, docs/kotlin/sign/dapp-usage.md, docs/kotlin/sign/wallet-usage.md, sidebars.js
Should be merged after: https://github.com/WalletConnect/walletconnect-docs/pull/267
=> Kotlin RelaClient docs

docs/introduction/cloud.md
Updates relay connection error codes, as changed in https://github.com/WalletConnect/rs-relay/pull/461
=> Update relay error codes

docs/specs/pair/client-api.md
- As discussed during the SDK call on 26.09.2022
=> feat(client-api): adds additional lifecycle methods

docs/introduction/auth.md
=> Improve auth intro

docs/specs/README.md, docs/specs/pair/rpc-methods.md
=> Pairing api

docs/advanced/migrating-from-v1.0.md, docs/readme.md
=> Fix: typos

docs/swift/auth/app-usage.md, docs/swift/auth/wallet-usage.md, docs/swift/core/pairing-usage.md, docs/swift/sign/dapp-usage.md, docs/swift/sign/wallet-usage.md
- Metadata removed form Auth configuration
- Signer's Type argument documented
=> [Auth] Auth configuration docs updated

docusaurus.config.js
=> show last update time

docs/introduction/web3modal.md, sidebars.js, versioned_docs/version-1.0/quick-start/dapps/web3modal.md, versioned_sidebars/version-1.0-sidebars.json
This PR adds a web3modal page to each version. It is being added to help with search and discoverability.
=> adds web3modal page

docs/javascript/auth/dapp-usage.md, docs/javascript/auth/installation.md, docs/javascript/auth/wallet-usage.md
=> feat(js): updates JS auth docs to align with v1.0.0

docs/swift/chat/installation.md, docs/swift/chat/usage.md, sidebars.js
Add documentation for swift chat alpha
=> Swift chat alpha

docs/javascript/chat/installation.md, docs/javascript/chat/usage.md, sidebars.js
=> feat(js): adds docs for Chat SDK alpha

docs/introduction/examples-and-resources.md
Add Auth Wallet and dApp example to intro Auth page
=> docs: add example in Examples and Resources

docs/specs/core/relay/relay-client-auth.md
Related to: https://github.com/WalletConnect/walletconnect-docs/issues/325#
=> Add missing consts

docs/advanced/chain-ecosystem-onboarding.md, sidebars.js
New page for Chain Ecosystem Onboarding added per [Luther's Request](https://walletconnect.slack.com/archives/C03US3FRU9L/p1662126193986549)
=> add new doc for onboarding chains

docs/javascript/guides/examples-and-resources.md
Add Chat example to /javascript/guides/examples-and-resources
=> docs/ add chat example

docs/web3modal/about.md, docs/web3modal/configuration.md, docs/web3modal/html-js/actions.md, docs/web3modal/html-js/installation.md, docs/web3modal/react/hooks.md, docs/web3modal/react/installation.md, docs/web3modal/standalone.md, sidebars.js
Updated all existing sections and added following new ones
- Html & Js usage
- Standalone usage
- Configuration
=> Update web3modal documentation

docs/javascript/core/pairing-api.md
=> fix(pairing): fix property access for events snippet

docs/javascript/sign/installation.md, docs/javascript/sign/wallet-usage.md
Add note to encourage wallets to also integrate Auth
=> Update Sign docs

docs/web3modal/configuration.md, docs/web3modal/html-js/actions.md, docs/web3modal/react/hooks.md
Documentation updates related to https://github.com/WalletConnect/web3modal/pull/731
=> Update web3modal config docs

docs/swift/auth/dapp-usage.md, docs/swift/auth/signer-configuration.md, docs/swift/auth/wallet-usage.md
Issue: https://github.com/WalletConnect/WalletConnectSwiftV2/issues/592
PR: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/607
Discussion: https://github.com/WalletConnect/WalletConnectSwiftV2/pull/612
=> [Auth] Swift SignerFactory docs

docs/web3modal/about.md, docusaurus.config.js, sidebars.js
Re opened PR because some changes did not get passed.
https://github.com/WalletConnect/walletconnect-docs/pull/335
=> Add w3m to js

docs/web3modal/html-js/actions.md, docs/web3modal/html-js/components.md, docs/web3modal/html-js/installation.md, docs/web3modal/react/components.md, docs/web3modal/react/hooks.md, docs/web3modal/react/installation.md
- New wagmi chain imports
- New hooks / actions
- Expose web3 button component props
=> Update web3modal docs

docs/web3modal/configuration.md, docs/web3modal/html-js/actions.md, docs/web3modal/html-js/components.md, docs/web3modal/react/components.md, docs/web3modal/standalone/installation.md
Docs associated to https://github.com/WalletConnect/web3modal/pull/770
=> web3modal beta.10 documentation updates

docs/javascript/auth/wallet-usage.md
Updated Wallet docs as per https://github.com/WalletConnect/walletconnect-docs/pull/355
=> refactor: auth multi address usage

docs/advanced/echo-server.md, docs/readme.md, sidebars.js
Remove reference to Sign 2.0 and Auth
=> remove 2.0 and auth from web3modal

docs/kotlin/auth/wallet-or-responder-usage.md
=> [docs] Fix typo

docs/specs/clients/auth/rpc-methods.md, docs/specs/clients/sign/rpc-methods.md
- expiry param validation
- TTL extension
=> [Sign] Request expiry instructions

docs/web3modal/about.md
Add Community SDKs and Plugins to Web3Modal
- Flutter/Dart
- Bubble NoCode Solution
=> Add Integrations Section to Web3Modal

docs/specs/clients/push/data-structures.md, docs/specs/clients/push/wallet-client-api.md
* add account to Push subscription data structure
* add getMessageHistory to WalletClient
=> Update Push spec

docs/specs/clients/core/relay/relay-client-api.md, docs/specs/servers/relay/relay-network.md, docs/specs/servers/relay/relay-server-api.md
Adding more context regarding relay network and messages
=> Relay Network & Messages

docs/advanced/migrating-from-v1.0.md
- rewords a couple of sentences to improve clarity
- add appropriate comma usage
=> chore: improve grammar in v1 migration docs

docs/javascript/web3wallet/wallet-usage.md
Added more context for when wallets are approving session requests.
=> Add instructions on how to approve a session request

docs/javascript/sign/wallet-usage.md
Added spaces in the object to improve readability.
=> Improve code block readability

docs/javascript/web3wallet/wallet-usage.md
- add reject response
- add json key to approval response
=> Add Reject response to code block

package.json, yarn.lock
Changelog https://docusaurus.io/changelog/2.3.0
=> upgrade docusaurus to 2.3.0

docs/advanced/migrating-from-v1.0.md
Adding wording that min version requirement is 2.1.1
=> Add min versioning for `version` in web3modal

docs/specs/servers/cast/cast-server-api.md
Update to the cast docs.
Added auth header with project_id. 
Temporarily as just string, but proper auth needs to be discussed.
Added response to the `/notify`
=> Update cast docs.

docs/specs/clients/push/dapp-client-api.md, docs/specs/clients/push/wallet-client-api.md
=> fix(push-spec): renames DappClient `delete -> deleteSubscription`

docs/javascript/push/dapp-usage.md, docs/javascript/push/wallet-usage.md
* fix: improve prerequisites description, link to w3w for wallet usage
* feat(push): updates JS dapp usage to include cast server usage flows
* General improvements and clarifications
=> feat(push-docs): updates dapp usage to include cast server flows, updates wallet usage

docs/javascript/providers/universal.md
As part of my [RN PR](https://github.com/WalletConnect/react-native-examples/pull/12), @bkrem suggested to add more explicit `console.log ` messaging so am also adding to documentation. 
This benefits developers to have clearer debugging.
=> Update Universal Provider code 

docs/web3modal/react/installation.md
=> Update broken NextJS example links

docs/advanced/migrating-from-v1.0.md
We finalized our support for Dynamic's wallet adapter! 🎉
=> Adding a guide for the Dynamic wallet adapter

docs/web3modal/about.md, docs/web3modal/html-js/installation.md, docs/web3modal/react/installation.md, docs/web3modal/standalone/installation.md, sidebars.js, src/css/custom.css
- Created Advanced Usage and Usage sections
- Resized Web3Modal Image
- Refactored Web3Modal description into features
- Removed community plugins by referencing awesome-walletconnect [TODO](https://github.com/WalletConnect/awesome-walletconnect/issues/1)
=> Rearrange Web3Modal Packages

docs/javascript/chat/usage.md
- Update the chat client doc to reflect new usage
=> Update chat docs per new spec

docusaurus.config.js
closes https://github.com/WalletConnect/web3modal/issues/929
=> Update discord link

docs/flutter/dapps/auth/dapp-usage.md, docs/flutter/dapps/auth/installation.md, docs/flutter/dapps/sign/dapp-usage.md, docs/flutter/dapps/sign/installation.md, docs/flutter/wallets/installation.md, docs/flutter/wallets/wallet-usage.md
Added flutter specific documentation (md) files.
This PR combined with #492 should get the flutter docs in place, and up to date.
=> Added flutter specific docs, not displayed on sidebar

docusaurus.config.js, sidebars.js
- Remove double version dropdown
- Add github link back to header
- Add link to swift docs back
- Add sidebar logo to flutter page
=> fix github link, swift docs, flutter sidebar

versioned_docs/version-1.0/smart-wallets.md
In preparation of porting this page to the `/2.0/` docs
=> fix(sc-wallets): corrections and readability tweaks

docs/cloud/relay.md
People often ask about projectid usage so adding a relay/projectid best practices section to help.
=> relay best practices

docs/web3modal/options.md
- Remove "if `projectId` is not included' text
- Add periods, update abbreviations
=> Docs clean up

docs/specs/clients/chat/spam-protection.md, docs/specs/clients/push/spam-protection.md, docs/specs/meta-clients/web3inbox/spam-protection.md
- Add push specific spam protection doc
- Add chat specific spam protection doc
- Add web3inbox specific spam protection doc
=> Add docs for spam protection in 3 SDKs

docs/flutter/dapps/dapp-auth-usage.md, docs/javascript/auth/dapp-usage.md
- Adds missing `type` field to auth request
- Format auth file with prettier
=> [auth] Add `type` field to request, format

docs/specs/clients/chat/chat-authentication.md, docs/specs/clients/chat/invite-keys.md, docs/specs/clients/push/push-authentication.md, docs/specs/servers/keys/identity-keys.md
Requires #527 to be merged
I would love everyone to approve as this affects push and chat specs and everyone needs to acknowledge the change
=> feat: Add act field to did-jwt claims

docs/specs/clients/sync/client-api.md
Update Client API for Sync API based on @devceline feedback 💪
=> Sync API changes

docs/javascript/push/wallet-usage.md
- To-be-merged once `push-client@0.7.0` has been released.
=> docs(js-push): adds documentation for onSign callback

docs/javascript/web3wallet/wallet-usage.md
Added JS auto namespaces usage docs
=> feat: JS auto namespaces usage docs

docs/web3modal/html-js/components.md, docs/web3modal/react/components.md
- Add docs for the new w3m qrcode component
=> Add docs for qrcode w3m component

docs/reactnative/Introduction.md, docs/reactnative/web3modal/dapp-usage.md, docs/reactnative/web3modal/installation.md, docs/reactnative/web3wallet/Installation.md, sidebars.js
Added docs for the new web3modal sdk for react-native.
TODO:
=> feat: Web3Modal react-native docs

docs/web3modal/html-js/installation.md
`getSigner` does not exist, I believe it was supposed to be `fetchSigner`
https://wagmi.sh/core/actions/fetchSigner
=> Fix HTML docs

docs/specs/clients/push/data-structures.md, docs/specs/clients/push/rpc-methods.md, docs/specs/servers/cast/cast-server-api.md
Changing the notification struct to allow Notify Server to distinguish between different notification types.
=> fix: update notification data structure

docs/reactnative/web3modal/dapp-usage.md, docs/reactnative/web3modal/installation.md
Updated `@web3modal/react-native` docs with alpha 2 changes
=> docs: updated w3m-rn docs

docs/web/chat/installation.md, docs/web/push/installation.md
Add note regarding install for Loki
=> add install steps for loki

docs/web3modal/html-js/installation.md, docs/web3modal/react/installation.md
- Update wagmi installation and setup instructions
=> Web3Modal v2.4 (quick docs)

docs/specs/clients/core/sync/sync-protocol.md
- Note that updates in the sync protocol should be optimistic to ensure better UX
=> Note optimisic updates

docs/specs/readme.md, vercel.json
Update broken links on https://docs.walletconnect.com/2.0/specs/
=> update broken links

docs/specs/servers/cast/cast-server-api.md
Proposal of some management endpoints to control the webhooks. 
Adding requested field to webhook payload.
=> feat: add webhooks management and dapp url to webhook payload

docs/specs/clients/push/dapp-client-api.md, docs/specs/clients/push/push-proposal.md, docs/specs/clients/push/push-subscription.md, docs/specs/clients/push/rpc-methods.md, docs/specs/clients/push/wallet-client-api.md
This PR includes the milestone 2A from the Stage 2 of "The Big Refactor" without including the renaming
=> [specs] remove wc_pushRequest and add wc_pushPropose

docs/web3modal/polkadot/dapp-integration-guide.md
* adds additional parachain caip ids as examples
* adds parachain example client request
=> Add polkadot parachain caip id examples

docs/advanced/migration-from-v1.x/dapps.md
Basic content fix for ConnectKit section
=> fix(migration/dapps): minor typo for connectkit

docs/advanced/migration-from-v1.x/dapps.md
Added links to web3modal ethereum-provider
=> fix(migration/ethereum-provider): added links to web3modal ethereum provider

docs/reactnative/web3modal/dapp-usage.md, docs/reactnative/web3modal/options.md
* added theme mode prop 
* added redirect in metadata
=> docs: w3m/rn alpha.6 updates

docs/web/providers/ethereum.md
Add: `optionalMethods`, `optionalChains`, and `optionalEvents`
Reference: https://github.com/WalletConnect/walletconnect-monorepo/blob/a0540de4fe8695214ff445a47ddf7e23659d0f39/providers/ethereum-provider/src/EthereumProvider.ts#L62
=> Add optional options to example

docs/specs/clients/core/relay/relay-client-api.md
I've added the specification for the extended Json RPC Id.
=> Client-Server Extended Json RPC Id

docs/kotlin/sign/wallet-usage.md
hopefully in time to help elucidate the intended behavior for [this guy in the discord](https://discord.com/channels/492410046307631105/1054741522664398949)
=> [docs] to clarify new CAIP-25 update section in kotlin

docs/advanced/migration-from-v1.x/dapps/dapp-checklist.md, docs/web/providers/ethereum.md
=> Chore: Add more information for Optional chains + methods

docs/web3inbox/about.md, docs/web3inbox/about.mdx, sidebars.js
- Add overview of web3inbox
- Add web3inbox to sidebar
=> Add overview page for web3inbox

docusaurus.config.js
Help prevent broken links
https://docusaurus.io/docs/api/docusaurus-config#onBrokenMarkdownLinks
=> Help prevent broken links

docs/web3modal/about.mdx
As per https://github.com/WalletConnect/walletconnect-docs/issues/802
=> RN links 404

docs/advanced/migration-from-v1.x/dapps/dapps.md
Updated instructions for web3modal v2 
wagmi code was outdated.
=> fix(migration/dapps): Updated instructions for web3modal v2

docs/specs/servers/relay/relay-server-rpc.md
Closes https://github.com/WalletConnect/walletconnect-docs/pull/775
Closes https://github.com/WalletConnect/rpc-proxy/issues/171
=> fix(relay): docs not matching implementation

docs/reactnative/walletconnectmodal/options.md
* Added `explorerRecommendedWalletIds` and `explorerExcludedWalletIds` props
=> feat: added new props to rn sdk

docs/advanced/migration-from-v1.x/explorer-submission.md, docs/advanced/migration-from-v1.x/wallets/wallet-checklist.md
=> fix: removed old web3modal lab links

docs/web/web3modal/react/wagmi/hooks.mdx
Change `useContract` to`useConnect` as useContract hook has been removed from from the hooks documentation
=> Change `useContract` to`useConnect`

docs/specs/servers/cast/cast-server-api.md
Adding authentication information for Cast endpoints.
=> chore: add authentication docs

docs/reactnative/walletconnectmodal/installation.md
- Updated installation steps for new expo 49
=> chore: added expo49 additional setup in modal rn

docs/ios/sign/dapp-usage.md
Fix from working with hackers at EthGlobal Paris
=> Update swift dapp-usage.md

docs/reactnative/walletconnectmodal/installation.md, docs/reactnative/walletconnectmodal/options.md
* Added custom shim for expo48 in a new code block
* Changed steps order for expo49
* Added new `accentColor` prop
=> RN - added custom shim in a new code block

docs/specs/clients/push/error-codes.md
- Add error code if user has existing sub
=> Add error code if user has existing sub

docs/web3modal/platforms/html.mdx
Adding viem + html section on Web3Modal v3
notion [link](https://www.notion.so/walletconnect/Web3Modal-v3-dogfooding-plan-f8ab6f6be880413d9f97d9b30c7e3be8?pvs=4#5a3e31d23e17463fb3f7393b4c4e50f1)
=> feat: add html section for web3modal v3

docusaurus.config.js
=> Chore:banner copy

docs/components/Home/Banner.js, docs/readme.mdx
=> Chore: Copy Changes

docs/api/auth/dapp-usage.md, docs/api/auth/resources.mdx, docs/api/auth/wallet-usage.md, docs/api/chat/usage.mdx, docs/web3inbox/resources.mdx, docs/web3inbox/usage.mdx
Updating following [notion](https://www.notion.so/walletconnect/APIs-Android-5c4440999d844031b2ee2a6fc7793fa9)
=> fix: android sections update links

docs/advanced/walletconnectmodal/about.mdx, docs/advanced/walletconnectmodal/options.mdx
* Added instructions to enable wallet detection in WalletConnectModal
* Added new `accentColor` prop
=> WalletConnectModal RN installed wallets detection

src/css/custom.css
=> Improved tab/toggle styling

docs/components/PlatformTabs.js, docs/web3modal/html/wagmi/installation.mdx, docs/web3modal/react/wagmi/installation.mdx, docs/web3modal/v3/about.mdx, docs/web3modal/v3/html.mdx, docs/web3modal/v3/html/about.mdx, docs/web3modal/v3/html/options.mdx, docs/web3modal/v3/html/theming.mdx, docs/web3modal/v3/options.mdx, docs/web3modal/v3/react.mdx, docs/web3modal/v3/react/about.mdx, docs/web3modal/v3/react/options.mdx, docs/web3modal/v3/react/theming.mdx, docs/web3modal/v3/theming.mdx, docs/web3modal/v3/vue.mdx, docs/web3modal/v3/vue/about.mdx, docs/web3modal/v3/vue/options.mdx, docs/web3modal/v3/vue/theming.mdx, sidebars.js, src/css/custom.css
TODOS/IMPROVEMENTS:
**Additional Features from [Release](https://github.com/WalletConnect/web3modal/releases/tag/3.0.0-alpha.4):**
=> feat: add the new features of Web3Modal v3-alpha.4

docs/web3inbox/usage.mdx
to be merged after notify refactor is completed
=> Web3inbox swift

docs/advanced/migration-from-v1.x/dapps/dapps.md, docs/advanced/walletconnectmodal/about.mdx
* added @react-native-community/netinfo to wcm-rn docs
=> chore: updated wcm-rn docs

src/css/custom.css, src/theme/Admonition/index.js, src/theme/Admonition/styles.module.css
=> fix: upgraded admonitions style

docs/web3wallet/verify.mdx
Adds a high-level description of the new `isScam` annotation.
Needs update in "Wallet Usage" once the SDKs expose the flag.
=> feat(verify): scam

docs/web3wallet/wallet-usage.mdx
=> Fix chainChanged example in wallet-usage.mdx

docs/api/core/pairing.mdx, docs/components/PlatformTabs.js, docs/web3wallet/about.mdx, docs/web3wallet/wallet-usage.mdx
Added a C# tab, this way we can add more specific Unity docs in the future
Also renamed some tabs from Unity to C#, as the context makes more sense (Web3Wallet is not yet in `WalletConnectUnity`)
=> Add C# tab, rename tabs from unity to csharp

docs/web3inbox/about.mdx, docs/web3inbox/core-components/about.mdx, docs/web3inbox/core-components/api.mdx, docs/web3inbox/core-components/usage.mdx, docs/web3inbox/demo.mdx, docs/web3inbox/embedded-widget/about.mdx, docs/web3inbox/embedded-widget/usage.mdx, docs/web3inbox/resources.mdx
- Added Quickstart Guide
- Moved warning up
=> fix: tweaks for W3I homepage

docs/web3modal/about.mdx
- Add new frameworks to Web3Modal overview for WalletConnectModal
- Restructure the order
- Brief explanation of WalletConnectModal
=> added new frameworks for walletconnectmodal

docs/web3inbox/about.mdx, docs/web3inbox/core-components/api.mdx, docs/web3inbox/core-components/usage.mdx, sidebars.js
Focus on the hooks in the docs, remove mention of widget as it is not as ready as we would like it to be
=> Web3inbox hooks focus

docs/web3inbox/core-components/api.mdx, docs/web3inbox/core-components/usage.mdx
- Add examples for onSign
- Show the hooks in play with a react component
=> Add examples for onSign

docs/web3inbox/core-components/api.mdx, docs/web3inbox/core-components/usage.mdx
- Clarify that `register` needs to be called even if account is registered
=> Update register stop docs

docs/advanced/providers/ethereum.md
=> Typo: EIP-1993 -> EIP-1193

docs/web3modal/flutter/actions.mdx, docs/web3modal/flutter/custom-chains.mdx, docs/web3modal/flutter/custom-wallets.mdx, docs/web3modal/flutter/installation.mdx, docs/web3modal/flutter/options.mdx, docs/web3modal/flutter/theming.mdx, sidebars.js
Just minor adjustment on Web3Modal documentation for Flutter
=> [Flutter] Adjustments on Web3Modal docs

docs/web3wallet/notify/installation.mdx, docs/web3wallet/notify/spam-protection.mdx, sidebars.js
Documents our current and expected plan for notification spam protection.
=> feat: notify spam protection

sidebars.js
=> fix: moved migration to advanced

docs/web3wallet/wallet-usage.mdx
=> fix: added polyfill warning for RN

docs/web3modal/flutter/installation.mdx, docs/web3modal/flutter/options.mdx
- Added more information to get started with flutter
=> More info to get started with Flutter

docs/web3modal/flutter/custom-chains.mdx, docs/web3modal/flutter/custom-wallets.mdx, docs/web3modal/flutter/installation.mdx
- Minor docs modifications to reflect changes
=> [Flutter] Custom chains page update

docs/web3modal/react-native/about.mdx
* Added installed wallet detection steps
* Added expo setup config
=> W3M RN updates

sidebars.js
fixes: https://github.com/WalletConnect/walletconnect-docs/issues/1103
=> [Swift] fix: w3m-swift example link

docs/web3modal/javascript/options.mdx, docs/web3modal/react/options.mdx, docs/web3modal/vue/options.mdx
- Added exclude wallets feature for Web3Modal SDK Web
- Added warning of affected functionality
=> add exclude wallets feature

docs/advanced/providers/universal.md
Addresses https://github.com/WalletConnect/walletconnect-docs/issues/1108
=> fix Universal Provider example

docs/web3modal/javascript/wagmi/about/implementation.mdx, docs/web3modal/react/wagmi/about/implementation.mdx, docs/web3modal/vue/wagmi/about/implementation.mdx
This pull request updates the Web3Modal section by including information about Wagmi connectors and providers. 
closes: #1096
=> Added more info in web3model section about custom/wagmi connecters

docs/api/notify/usage.mdx, docs/web3inbox/frontend-integration/api.mdx
- update to new specs of w3i core components
=> feat: use new core component api

docs/advanced/migration-from-v1.x/dapps/dapp-checklist.md, docs/advanced/migration-from-v1.x/dapps/dapps.md, docs/advanced/migration-from-v1.x/wallets/wallets.md, docs/advanced/multichain/polkadot/dapp-integration-guide.md, docs/advanced/multichain/polkadot/wallet-integration-guide.md, docs/api/auth/dapp-usage.md, docs/api/auth/wallet-usage.md, docs/api/chat/usage.mdx, docs/api/notify/usage.mdx, docs/api/sign/dapp-usage.md, docs/api/sign/wallet-usage.md, docs/specs/clients/chat/usage-of-sync-api.md, docs/specs/clients/core/sync/sync-protocol.md, docs/specs/clients/core/verify/verify-client-api.md, docs/specs/clients/notify/notify-authentication.md, docs/specs/servers/relay/relay-server-rpc.md, docs/specs/servers/verify/veriy-server-enclave.md, docs/web3inbox/frontend-integration/api.mdx, docs/web3modal/flutter/custom-wallets.mdx, docs/web3modal/v2/_partials/customisation/customWagmiWalletsIntro.mdx, docs/web3modal/v2/javascript/wagmi/installation.mdx, docs/web3wallet/notify/usage.mdx, docs/web3wallet/verify.mdx, docs/web3wallet/wallet-usage.mdx
Hi,
This pull request addresses minor issues in the documentation by fixing typos. These changes aim to improve the overall clarity and readability of the documentation for a better user experience.
Please review my PR. Thank you for your time and consideration.
=> docs: fix typos

README.md
crawls-> crawl
when->while and removed unnecessary commas.
=> Corrected few minor issues in the README.md file

docs/web3modal/react-native/about.mdx
=> fix: added admonition for import order

docs/web3modal/javascript/ethers/about/implementation.mdx
=> chore: update implementation.mdx

docs/quickstart.mdx
=> fix: added library option for quickstart

docs/web3modal/react-native/about.mdx
* Updated version to Beta
* Added `@walletconnect/react-native-compat` polyfill step
* Moved expo-48 extra step in a detail component
=> chore: updated w3m rn docs

docs/advanced/walletconnectmodal/about.mdx, docs/advanced/walletconnectmodal/usage.mdx
* Moved expo 48 extra step to a detail component
* Removed expo 49 extra steps
* Fixed usage code
=> chore: moved expo48 extra step to detail component, improved usage

docs/web3modal/javascript/actions.mdx, docs/web3modal/react/hooks.mdx, docs/web3modal/vue/composables.mdx
Disconnect function and hook for Web3Modal ethers
closes https://github.com/WalletConnect/walletconnect-docs/issues/1168
=> add disconnect feature - ethers

docs/web3modal/nextjs/about.mdx
- refactor: fix Webpack config code snippet typo in Next.js docs
=> refactor: update nextjs webpack config code snippet

README.md
=> fix: added to README

docs/web3modal/about.mdx
We are working on shipping transaction history in the web3modal feature soon. This PR includes some document updates for it.
=> chore: add transaction history to the features list

docs/web3modal/react-native/about.mdx
* Changed needed package to enable wallet detection
=> chore: added note in wallet detection steps

docs/web3inbox/about.mdx, docs/web3inbox/demo.mdx, docs/web3inbox/sending-notifications.mdx
app.web3inbox.com now supports push notifications, so updating the language to mention that
=> feat: app.web3inbox.com PWA

docs/web3inbox/sending-notifications.mdx
- fix missing content-type header
- add get subscribers endpoint
- other wording and structure improvements
- document each field, allowing copy/paste
- provide real account ID and title/body examples
- remove `icon` field as this will be replaced
=> feat: get subscribers endpoint & missing content-type

docs/advanced/providers/ethereum.md, docs/advanced/providers/universal.md, docs/advanced/walletconnectmodal/about.mdx
closes https://github.com/WalletConnect/walletconnect-docs/issues/1214
=> add admonition

docs/web3wallet/wallet-usage.mdx
=> Fixes typo 'accountChanged'

.github/ISSUE_TEMPLATE/BUG-REPORT.yml, .github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml, .github/ISSUE_TEMPLATE/config.yml
This pull request introduces various issue templates to this repository, encompassing formats such as Bug reports, Feature request, Ask a Question, and View our FAQs.
fixes: #1127
=> added issue templates

docs/web3inbox/about.mdx, docs/web3inbox/authorization-signatures/about.mdx, docs/web3inbox/authorization-signatures/all-apps.mdx, docs/web3inbox/authorization-signatures/this-app.mdx, docs/web3inbox/demo.mdx, docs/web3inbox/sending-notifications.mdx
Responding to feedback from [here](https://github.com/WalletConnect/walletconnect-docs/commit/1cd47f82e930b2b49132f7cf1ddbb6550e76d51d#)
=> fix: copy tweaks

docs/web3modal/react-native/hooks.mdx
Added an example using useContractRead hook
Related with: https://github.com/WalletConnect/walletconnect-docs/issues/1186
=> chore: added example to read contract

sidebars.js
=> fix: advanced sidebar hierarchy

docusaurus.config.js, src/css/custom.css
=> fix: added dashboard button for cloud

docusaurus.config.js, src/css/custom.css
Changed default search view to default to chat
=> fix: changed default search view to chat

docs/web3inbox/frontend-integration/api.mdx
Dev asked how to do this, was undocumented
=> fix: document isSubscribing and isUnsubscribing

docs/web3wallet/push-notifications.mdx
added `react-native` push notificaiton setup & usage docs
=> feat: rn notifications

docs/web3modal/about.mdx, docs/web3modal/v2/javascript/wagmi/actions.mdx, docs/web3modal/v2/javascript/wagmi/components.mdx, docs/web3modal/v2/javascript/wagmi/custom-chains.mdx, docs/web3modal/v2/javascript/wagmi/custom-wallets.mdx, docs/web3modal/v2/javascript/wagmi/installation.mdx, docs/web3modal/v2/javascript/wagmi/options.mdx, docs/web3modal/v2/javascript/wagmi/theming.mdx, docs/web3modal/v2/react/wagmi/components.mdx, docs/web3modal/v2/react/wagmi/custom-chains.mdx, docs/web3modal/v2/react/wagmi/custom-wallets.mdx, docs/web3modal/v2/react/wagmi/hooks.mdx, docs/web3modal/v2/react/wagmi/installation.mdx, docs/web3modal/v2/react/wagmi/options.mdx, docs/web3modal/v2/react/wagmi/theming.mdx
=> Added w3m v2 warning and upgrade guide link

docs/web3wallet/notify/usage.mdx
This documents how to use Notify Client for React Native wallets.
=> chore(add-rn-docs): add Notify API docs for React Native wallets

docs/web3modal/javascript/siwe/usage.mdx, docs/web3modal/nextjs/siwe/next-auth.mdx, docs/web3modal/nextjs/siwe/usage.mdx, docs/web3modal/react/siwe/usage.mdx, docs/web3modal/vue/siwe/usage.mdx
Latest Web3Modal version supports siwe out of the box.
=> chore(remove-alpha): remove alpha version from siwe install

docs/advanced/walletconnectmodal/usage.mdx
=> Added docs on interaction with RPC endpoint and smart contracts from Unity

docs/api/notify/migration-guide.mdx, docs/api/notify/usage.mdx, sidebars.js
Update docs to showcase new registration methodology per the new specs:
- https://github.com/WalletConnect/walletconnect-specs/pull/177
- https://github.com/WalletConnect/walletconnect-specs/pull/178
- https://github.com/WalletConnect/walletconnect-specs/pull/181
And new JS client:
- https://github.com/WalletConnect/notify-client-js/pull/82
**Note**: Will merge as soon as new notify client goes live.
=> feat: show new way to register

docs/readme.mdx, sidebars.js
Reorder SDKs so that the order matches the product list on the website. [Context](https://walletconnect.slack.com/archives/C03US3FRU9L/p1703205308864029)
=> chore: reorder Web3Inbox and Web3Wallet

docs/cloud/verify.md, docs/web3inbox/cloud-setup.mdx
Add steps for Verify API and publishing the Explorer listing.
=> Update web3inbox setup steps

docs/web3modal/react-native/about.mdx, docs/web3modal/react-native/options.mdx
Add coinbase integrations steps for Web3Modal React Native
=> Add coinbase steps for Web3Modal React Native

docs/web3modal/react-native/about.mdx
Added coinbase integrations steps as a new section
=> chore: added coinbase steps as a section

docs/advanced/walletconnectmodal/about.mdx, docs/advanced/walletconnectmodal/usage.mdx
Added `react-native-compat` in the needed package list
=> chore: added new step for wcm rn installation

docs/web3inbox/cloud-setup.mdx
=> Chore: Add CORS information for Cloud/Notify

docusaurus.config.js
=> Chore: Revert Algolia as default

docs/web3modal/react-native/about.mdx
Added missing dependency in web3modal expo installation steps
=> chore: added expo-application in install steps

docs/web3inbox/cloud-setup.mdx
[Context](https://walletconnect.slack.com/archives/C044SKFKELR/p1706285643522839?thread_ts=1706275447.442049&cid=C044SKFKELR)
=> fix: raise importance of the need to create notification types first

docs/components/YoutubeEmb.js, docs/web3modal/react/wagmi1/hooks.mdx
Added youtube tutorial link given in the issue in Hooks under Wagmi v1 section.
closes https://github.com/WalletConnect/walletconnect-docs/issues/1335
=> Youtube tutorial about React Hooks

docs/web3inbox/about.mdx
=> chore: revert

docs/web3modal/react-native/options.mdx
* Added custom wallet option to web3modal react-native
=> chore: added custom wallets option

docs/web3modal/about.mdx, docs/web3modal/react-native/about.mdx, docs/web3modal/react-native/ethers5/about/implementation.mdx, docs/web3modal/react-native/ethers5/about/installation-expo.mdx, docs/web3modal/react-native/ethers5/about/installation.mdx, docs/web3modal/react-native/ethers5/hooks.mdx, docs/web3modal/react-native/hooks.mdx, docs/web3modal/react-native/options.mdx, docs/web3modal/react-native/resources.mdx, docs/web3modal/react-native/wagmi/about/implementation.mdx, docs/web3modal/react-native/wagmi/about/installation-expo.mdx, docs/web3modal/react-native/wagmi/about/installation.mdx, docs/web3modal/react-native/wagmi/hooks.mdx
* Added new docs for web3modal + ethers5 for React Native
* Splitted docs in wagmi1 and ethers5
=> chore: added ethers5 docs for react native

docs/web3wallet/notify/usage.mdx, docs/web3wallet/push-notifications.mdx
- `fetchMessages` method
- messages events
=> [Notify] Swift docs updated

docs/web3inbox/frontend-integration/usage.mdx
=> Messages Component for W3I SDK Usage

docs/api/notify/usage.mdx, docs/web3inbox/frontend-integration/api.mdx, docs/web3inbox/frontend-integration/usage.mdx, docs/web3wallet/notify/usage.mdx
- update getting started usage for vanilla
- fix minor comments on original PR
=> chore: update getting started usage for vanilla

docs/api/notify/usage.mdx, docs/web3inbox/frontend-integration/api.mdx, docs/web3wallet/notify/usage.mdx
- add read/unread support in hooks
- add read/unread support for react/native
=> chore: add api for read unread

docs/web3inbox/frontend-integration/api.mdx, docs/web3inbox/frontend-integration/usage.mdx
Fixes that the additions were not backwards-compatible, and introduces a struct for future parameters which is easier to add parameters to in the future, as well as modeled after WAGMI's design.
Also adds read/unread to the usage page.
=> fix: read unread in usage, and backwards-compatible parameters

docs/web3modal/react-native/ethers/about/implementation.mdx, docs/web3modal/react-native/ethers5/about/implementation.mdx, docs/web3modal/react-native/hooks.mdx, docs/web3modal/react-native/options.mdx, docs/web3modal/react-native/wagmi1/about/implementation.mdx
* Added analytics props and hooks to Web3Modal React Native sdk
=> chore: added analytics prop for w3m rn

docs/web3modal/nextjs/about.mdx
=> Wrong import for useReadContract()

docs/advanced/rpc-reference/casper-rpc.md
This PR includes the RPC specification for the interaction of a dApp and a wallet in the context of the Casper Network.
=> Casper Network RPC spec

docs/web3inbox/frontend-integration/api.mdx
- Add note showing which versions of web3inbox core will support of eip1271
=> add note about eip1271 support in web3inbox

docs/web3modal/react-native/options.mdx
Added alpha tag to `enableAnalytics` option in W3M React Native docs
=> chore: added alpha tag to w3m analytics

docs/web3inbox/frontend-integration/api.mdx
Document ways for, mainly, wallets to manage subscriptions to different domains
=> Show Features Required By Wallets in W3I Hooks

docusaurus.config.js
Update the banner to share new features: Email Wallet & Onramp
=> refactor: update banner for new features

docs/web3modal/react/ethers5/triggermodal.mdx
=> Fix: Updated import link in documentation

docs/web3wallet/verify.mdx
* added react native tab for verify api
=> chore: added react native tab for verify api

docs/web3modal/react-native/about.mdx, docs/web3modal/react-native/ethers/about/coinbase.mdx, docs/web3modal/react-native/ethers/about/implementation.mdx, docs/web3modal/react-native/ethers/about/installation-expo.mdx, docs/web3modal/react-native/ethers5/about/coinbase.mdx, docs/web3modal/react-native/ethers5/about/implementation.mdx, docs/web3modal/react-native/ethers5/about/installation-expo.mdx, docs/web3modal/react-native/expo/additional-expo48.mdx, docs/web3modal/react-native/wagmi/about/coinbase.mdx, docs/web3modal/react-native/wagmi/about/implementation.mdx, docs/web3modal/react-native/wagmi/about/installation-expo.mdx, docs/web3modal/react-native/wagmi/about/installation.mdx, docs/web3modal/react-native/wagmi/email.mdx, docs/web3modal/react-native/wagmi/hooks.mdx, docs/web3modal/react-native/wagmi1/about/coinbase.mdx, docs/web3modal/react-native/wagmi1/about/implementation.mdx, docs/web3modal/react-native/wagmi1/about/installation-expo.mdx
* Added Wagmi 2 docs for React Native
* Moved Coinbase config to new files
* Moved expo additional config to a new file
=> chore: Added wagmi v2 docs for react-native

docs/cloud/blockchain-api.md
[Slack conversation](https://walletconnect.slack.com/archives/C03RR432R2R/p1716903267701629)
=> fix: clarify Blockchain API role

docs/web3wallet/wallet-usage.mdx
Relates to: https://github.com/WalletConnect/walletconnect-monorepo/pull/4346
=> feat: exposes `acknowledged` to update & extend

docs/web3modal/nextjs/wagmi/about/implementation.mdx
fix #1582  This pr updates the web3 modal docs for next js it had wrong dependency imports in the doc.
=> Update web3 Modal NextJs docs

docs/appkit/shared/socials.mdx, package-lock.json
* Add `walletFeatures` section to social & email accounts
=> :feat wallet features

docs/appkit/react-native/core/installation.mdx, docs/appkit/react-native/core/siwe.mdx, docs/appkit/react-native/wagmi/about/installation-expo.mdx, docs/appkit/react-native/wagmi/about/installation.mdx
Added alpha tag in wagmi v2 packages for RN
=> chore: added wagmi expo alpha tag

docs/appkit/unity/core/installation.mdx
=> fix: add missing `com.nethereum` scope to the AppKit installation docs

docs/appkit/react-native/core/hooks.mdx, docs/appkit/react-native/ethers/hooks.mdx, docs/appkit/react-native/ethers5/hooks.mdx, docs/appkit/react-native/wagmi/hooks.mdx, docs/appkit/react-native/wagmi1/hooks.mdx
* Added useWalletInfo hook for RN
* Added wagmi tab in hooks
=> chore: hook changes for RN

docs/appkit/react-native/core/installation.mdx, docs/appkit/react-native/core/options.mdx, docs/appkit/react-native/onboarding/email.mdx
* Added missing wagmi2 tabs in email and options docs for react native
* Added wagmi 2 and ethers 6 as supported libs
=> chore: added missing wagmi2 tabs

docs/appkit/react-native/core/installation.mdx
* Fixed coinbase connector install script
* Added alpha tag to wagmi2 connector
=> fix: fixed coinbase connector package

docs/walletkit/best-practices.mdx
* Replaced tabs with PlatformTabs so it remembers the selected platform
* Moved some platform specific links inside a PlatformTab
=> chore: improved best practices page

docs/appkit/react/core/custom-connectors.mdx
+ Update code for custom connector in react for wagmi and ethers.
Preview:
+ ethers: https://walletconnect-docs-git-feat-update-custom-17feee-walletconnect1.vercel.app/appkit/react/core/custom-connectors?platform=ethers
+ wagmi: https://walletconnect-docs-git-feat-update-custom-17feee-walletconnect1.vercel.app/appkit/react/core/custom-connectors?platform=wagmi
=> Feat: Update code for custom conn in react

docs/appkit/features/onramp.mdx, docs/appkit/features/solana.mdx, docs/appkit/features/swaps.mdx, docs/appkit/javascript/core/actions.mdx, docs/appkit/javascript/transactions/onramp.mdx, docs/appkit/next/core/hooks.mdx, docs/appkit/next/transactions/onramp.mdx, docs/appkit/overview.mdx, docs/appkit/react/core/hooks.mdx, docs/appkit/react/transactions/onramp.mdx, docs/appkit/shared/onramp.mdx, docs/appkit/vue/core/composables.mdx, docs/appkit/vue/transactions/onramp.mdx, sidebars.js
+ fix typo problems with On-Ramp
+ fix title tag from different pages
=> Fix: Title tag & typo issues in some meta tag titles

docs/appkit/react/core/siwe.mdx, docs/appkit/shared/siwe/code.mdx
Preview URL: https://walletconnect-docs-git-feat-improve-siwe-react-walletconnect1.vercel.app/appkit/react/core/siwe
=> Feat: Update SIWE React code in minimal example

docs/appkit/react-native/core/components.mdx, docs/appkit/react-native/core/installation.mdx, docs/appkit/react-native/core/options.mdx, docs/appkit/react-native/core/siwe.mdx, docs/appkit/react-native/ethers/about/implementation.mdx, docs/appkit/react-native/ethers/hooks.mdx, docs/appkit/react-native/ethers5/about/implementation.mdx, docs/appkit/react-native/ethers5/hooks.mdx, docs/appkit/react-native/onboarding/email.mdx, docs/appkit/react-native/wagmi/about/implementation.mdx, docs/appkit/react-native/wagmi1/about/implementation.mdx, docs/walletkit/react-native/mobile-linking.mdx, docs/walletkit/react-native/one-click-auth.mdx, docs/walletkit/react-native/resources.mdx
* added new android script for expo wallet detection for React Native
* replaced web3modal to appkit in React Native docs
* Added ios/android tabs for specific steps in RN
=> chore: RN docs improvements

docs/appkit/android/core/one-click-auth.mdx, docs/walletkit/android/link-mode.mdx, sidebars.js
PR introduces documentation for Link Mode for WalletKit and AppKit on Kotlin
**Ready for review but please do not merge for now**
=> Link Mode Kotlin Docs

docs/appkit/javascript/ethers/about/implementation.mdx, docs/appkit/javascript/ethers5/implementation.mdx, docs/appkit/next/ethers/about/implementation.mdx, docs/appkit/next/ethers5/implementation.mdx, docs/appkit/next/wagmi/about/implementation.mdx, docs/appkit/react/wagmi/about/implementation.mdx, docs/appkit/shared/onramp.mdx, docs/appkit/shared/options.mdx, docs/appkit/shared/swaps.mdx, docs/appkit/vue/ethers/about/implementation.mdx, docs/appkit/vue/ethers5/implementation.mdx, docs/appkit/vue/wagmi/about/implementation.mdx
- Introducing `enableSwaps` flag in the options and add integration section to the feature page
- Refactor all Onramp flags since the `enableOnramp` is true by default. And add `enableOnramp` to the options page.
=> refactor: add enableSwaps flag

docs/appkit/features/socials.mdx, docs/appkit/react/core/custom-connectors.mdx, docs/appkit/shared/socials.mdx
=> Add farcaster references

docs/walletkit/react-native/installation.mdx
Removed not needed dependencies from WalletKit React Native installation steps
=> chore: walletkit react native - installation steps

docs/appkit/migration/from-rainbowkit-next.mdx, docs/appkit/vue/core/installation.mdx, docs/appkit/vue/solana/about/implementation.mdx, docs/appkit/vue/solana/about/triggermodal.mdx, src/css/custom.css
+ It was not working because we have to add "rpc-websockets": "7.11.0", (not the latest)
+ Adjust design so appkit and walletkit enter in the same Row
preview: https://walletconnect-docs-git-feat-add-solana-vu-92614c-walletconnect1.vercel.app/appkit/vue/core/installation?platform=solana
=> Feat: add docs to use Appkit Solana with Vue

docs/advanced/security/content-security-policy.md
Update CSP to include new Verify Server endpoint usage.
=> fix: update CSP

docs/walletkit/react-native/usage.mdx, docs/walletkit/react-native/verify.mdx, docs/walletkit/web/installation.mdx, docs/walletkit/web/usage.mdx, docs/walletkit/web/verify.mdx
=> WalletKit JS & React Native fixes & improvements

docs/appkit/migration/from-anza-adapter-react.mdx, sidebars.js
+ Add anza adapter migration path
+ Add the migration path to the sidebar
https://walletconnect-docs-git-feat-migration-guide-anza-walletconnect1.vercel.app/appkit/migration/from-anza-adapter-react
=> feat: Add anza adapter migration path

docs/advanced/multichain/rpc-reference/solana-rpc.md
=> Fix on sonala-rpc md for better readability
