- quick-start/dapps/client.md
A comma was misplaced in a code sample. Opening this PR to fix it.
> Fix JS typo in Standalone Dapp Page

- docusaurus.config.js
Our docs site is versioned, with different content for v1 and v2 docs.
Currently, search for terms will show results from both v1 and v2, which can lead a user to out of date content.  For example, here is a search for `bridge` which shows mixed content from v1 and v2.
This change scopes the results depending on what version is selected.  If v1 is selected, search terms will be scoped to the v1 version.  If v2 is selected (by default), search is scoped to v2.   Scoping the results shows more relevant results from the latest version, rather than showing older or out of date results.
Here is the same query with contextual search added. It only shows mentions of bridge in v2 when searching from default/v2.
There is also a search page where the version can be explicitly set.
More details …
> Use contextual search to support versioned content

- docs/quick-start/dapps/client.md
Aligning the sample code with the options provided by the v2.0 `Client` API: https://github.com/WalletConnect/walletconnect-monorepo/blob/a22bee13df255ee59d338d600175250a3a0ef8aa/packages/types/src/client.ts#L14
* Changes `relayProvider -> relayUrl`
* Adds missing `projectId`
* Fixes step numbering
> docs(client): aligns sample code for `Client.init` with v2.0 API

- docusaurus.config.js
DocSearch, the search service that powers search, has migrated to Algolia.
This PR updates the credentials.
See the Docusaurus blog post for more details https://docusaurus.io/blog/2021/11/21/algolia-docsearch-migration
> Update algolia search credentials

- docs/protocol/tech-spec.md
Removing methods.
These were designed for a multi-protocol relayer, such as for example we would support Waku and WebRTC in parallel, but they are not currently being used.
> tech spec changes

- docusaurus.config.js
Adds simple privacy focused stats to docs.
The goal of Plausible is to understand overall trends in this websites traffic in a privacy-preserving manner, and is not to track individual visitors. Plausbile does not use cookies, does not generate any persistent identifiers and does not collect or store any personal or identifiable data. All of the data is aggregated data only and it has no personal information. All the site measurement is carried out absolutely anonymously. Read more about about [Plausible's data policy](https://plausible.io/data-policy).
Followed the [Plausible guide instructions](https://plausible.io/docs/docusaurus-integration) for Docusaurus.
> add plausible

- versioned_docs/version-1.0/bridge-server.md
The bridge server info described in the docs is no longer valid.
Removing for clarity.
> Remove bridge server info

- versioned_docs/version-1.0/mobile-linking.md
I've been investigating app link issues with WalletConnect on iOS and found that the corresponding native app isn't opened as expected in certain common scenarios, especially (but not exclusively) when using Ethers. Unfortunately there's no quick fix for it which means that developers will need some guidance on what the issue is and how to avoid it.
I should note that this documentation obviously isn't the ideal end state. @jxom is actively working on [better abstractions in wagmi](https://github.com/tmm/wagmi/pull/658) to deal with this problem and [I've been in contact with Ethers](https://github.com/ethers-io/ethers.js/discussions/3151) about this too to see whether we can get better access to its internals, but in the meantime it would be great for the WalletConnect docs to provide …
> Add iOS App Link Constraints section to Mobile Linking docs

- docusaurus.config.js
Update latest version to "release candidate" instead of beta.
> update v2 version to rc

- docs/swift/guides/mobile-linking.md
- sidebars.js
Ports the mobile linking doc from v1.
Creates a new Swift section called Guides 
(Follows the format started by Kotlin >> https://docs.walletconnect.com/2.0/kotlin/guides/mobile-linking)
> v2 iOS mobile linking guide

- docs/introduction/auth.md
- docs/javascript/auth/dapp-usage.md
- docs/javascript/auth/installation.md
- docs/javascript/auth/wallet-usage.md
- Dedupes contradictory and duplicated install steps
- Aligns formatting between dapp and wallet guides
- Tweaks code snippets based on recent spec changes
> docs(auth): integrate findings from dogfooding JS auth docs

- docs/introduction/push.md
- docs/introduction/sign.md
- versioned_docs/version-1.0/push-server.md
This PR adds deprecation notices for Push API support in v2 and directs users to the Echo Server spec which will be supported in the coming weeks
> Push Server Deprecation Notice

- docs/introduction/push.md
- docusaurus.config.js
- src/pages/index.js
- vercel.json
v2 is final, so this change makes makes v2 the current version!
Paths are now:
v2 - `/2.0/`
v1 - `/1.0/` 
A redirect was added from `/` to make `/2.0` the default start page.
NOTE: This PR breaks the permalinks for v1 docs since previously v1 content was at `/`, but now it is `/1.0`.  Vercel redirects were added to handle this.
> Make v2 the default docs version

- docs/advanced/relay-server.md
There's websites that open sockets to walletconnect without ever using walletconnect.
This will get expensive in dollar terms in the future.
This change is to depict that the relay will terminate clients that didn't subscribe to anything.
> feat(docs): defines relay close codes

- docs/specs/sign/session-proposal.md
Currently wallet waits to send settlement payload until dapp confirms that they received the proposal.
In the worst case e.g. for users in Australia far away from our writer nodes, steps 6 and 7 each take up to a second.
They don't need to be sequential. Hence, parallelizing this speeds up pairing experience by up to a second.
> feat: speed up pairing

- docs/introduction/cloud-explorer.md
Closes https://github.com/WalletConnect/registry-api-cf-workers/issues/58
- Adds `sdks` query parameter to params table
- Marks `version` query parameter as deprecated, as it is superseded by `sdks`
> docs(explorer-api): adds `sdks` param, mark `version` as deprecated

- docs/specs/README.md
- docs/specs/sign/migration.md
Deleting this page, since we no longer have any clients using the beta clients.
> delete old beta migration links

- docs/web3modal/about.md
- sidebars.js
Chad noticed Web3Modal isn't mentioned in JavaScript products, so I added all but the `About` page to JavaScript products.
Slack Conversation: https://walletconnect.slack.com/archives/C03US3FRU9L/p1668499446473969
> Add W3M to JavaScript products

- docs/specs/clients/auth/client-api.md
- docs/specs/clients/auth/data-structures.md
To support multi-account feature SDK should not store Account object. Account will be passed with `respond` method. 
This makes problematic to generate finalised SIWE message for clients. I suggest to open SIWEMessageFormatter interface to allow this: 
```swift
protocol SIWEMessageFormatting {
func formatMessage(from payload: PayloadParams, address: String) -> String?
}
```
> [Spec] Auth Multi Account

- docs/javascript/auth/dapp-usage.md
- docs/javascript/sign/dapp-usage.md
Previous example code still included `@walletconnect/qrcode-modal` in the Sign and Auth JavaScript dapps section in the docs. Updated docs to use `@web3modal/standalone`.
> refactor: update dapp example code to include standalone

- docs/kotlin/sign/dapp-usage.md
for dapp usage, it should call SignClient.setDappDelegate(dappDelegate)
> for dapp usage, it should call setDappDelegate

- docs/specs/clients/auth/README.md
> Add missing word in Auth API docs

- docs/javascript/sign/dapp-usage.md
- Add `relayUrl` as optional parameters to the dapp usage docs
> add optional params to dapp example

- docs/specs/clients/push/error-codes.md
To align with: https://github.com/WalletConnect/walletconnect-docs/blob/9bb84dfc3f84ba4dce0c67b81229e07feeffbcbd/docs/specs/clients/sign/error-codes.md#reason
Realised that we ended up with two `5000` codes being added yesterday, presumably a copy-paste mistake.
> fix(spec): corrects error code for Push `.userUnsubscribed` reason

- docs/advanced/glossary.md
- docs/javascript/sign/wallet-usage.md
- docs/specs/clients/sign/data-structures.md
- docs/specs/clients/sign/rpc-methods.md
- docs/specs/clients/sign/session-namespaces.md
- docs/swift/sign/dapp-usage.md
Removed all instances of `extension` when pertaining to an additional object in `namespaces`.
> Remove namespaces.extension

- docs/cloud/explorer.md
Closes #414
Enables API users to filter listings based on standards with the following pattern `standard_prefix-standard_id`
For example, to query dapp listings that support EIP712 or EIP3085:
`/v3/dapps?projectId=PID&standards=eip-712,eip-3085`
> feat(explorer-api): document standards query param

- docs/specs/clients/auth/data-structures.md
* Discord user `Moneta#7795` gracefully pointed out that the CAIP ID number in the spec is incorrect when referencing the CACAO standard.
* Also adds links to the CAIP spec itself.
> fix(specs): fixes wrong ID for CAIP-74 references and links to CAIP spec

- docs/advanced/faq.md
Added two FAQs
- How can we use a custom relay for our bridge without a WC URI parameter as the host?
- Why is self-hosting RPC nodes not an option at this time? Are there plans to make this possible in the future?
Other Update
- Updated `relayUrl` to include `wss:relay.` prefix
Proof read by Linda.
> add FAQs around self hosting

- docs/api/push.md
v1 Push has now been removed from v2, change the warning to a note so that people know they have to implement the [Echo Server spec](https://github.com/WalletConnect/echo-server/blob/main/spec/spec.md).
> fix: Push API Note

- docs/advanced/rpc-reference/cosmos-rpc.md
cosmos rpc seems to be built along cosmjs's offline signer/direct signer. However, there is a difference from the actual cosmjs interface.
Also, since cosmjs encodes most byte arrays to base64, we suggest replacing the existing hex-encoded part with base64.
- Base64 encode pubkey of `cosmos_getAccounts` response.
- Add public key to signature of `signAmino/signDirect` response.
- Fix some intent.
> Match cosmjs interface and fix intent

- docs/javascript/web3wallet/wallet-usage.md
The `@walletconnect/utils` package is referenced confusingly as `@walletconnect-utils`. This makes the package name more clear and easy for developers to import.
> Use more semantic package name that can be imported directly in npm

- docs/specs/clients/auth/rpc-methods.md
- docs/specs/clients/chat/rpc-methods.md
- docs/specs/clients/core/relay/relay-client-api.md
- docs/specs/clients/push/rpc-methods.md
- docs/specs/clients/sign/rpc-methods.md
- docs/specs/servers/relay/relay-server-rpc.md
Following the conversation at the Push weekly meeting. The prompt flag is redundant now that tags are used instead
> Remove Prompt Flag

- docs/javascript/sign/wallet-usage.md
> Update to signClient.core.pairing.pair()

- docs/web3modal/react/installation.md
Add the Web3Button to the installation page for a smoother experience. It allows developers to do everything on one page.
> Add Web3Button to Install

- docs/advanced/migrating-from-v1.0.md
This PR adds migration info for WC V2 Migration information for the @web3-onboard/walletconnect package
> Docs: WC V2 Migration information for @web3-onboard/walletconnect package

- docs/web3modal/html-js/installation.md
- docs/web3modal/react/installation.md
Context
- Ethers.js package updated to `v6`. wagmi relies on `v5`. 
- Similar to how wagmi docs have done it, have specified users to use `v5`
Wagmi [site](https://wagmi.sh/): `npm i wagmi ethers@^5`
> chore: update the ethers version

- docs/specs/clients/push/data-structures.md
- docs/specs/clients/push/wallet-client-api.md
- Add Push Message Record data structure
`id` - for PM uniqueness, allows to delete message
- Add deletePushMessage() method to Wallet Push Client
If you guys prefer, we can also make it flat in PushMessage
> add Push Message Record data structure

- docs/specs/clients/core/relay/relay-client-api.md
- docs/specs/servers/relay/relay-server-rpc.md
Allow the Relay server to act as the source of truth for when messages are published
> Add timestamp to received messages

- docs/web3modal/standalone/installation.md
Now pointing to the Next.js Example at 
https://github.com/WalletConnect/web3modal/tree/V2/examples/nextjs-standalone
> Update broken link for the React Example.

- docs/specs/clients/chat/client-api.md
- docs/specs/clients/chat/data-structures.md
The previous Invite structure was designed for the receiver of the invite not for the sender. Adds dedicated invite data structure for client `invite()` method.
> feat: Improve Invite structures

- docs/advanced/what-changed-from-v1.0.md
The sentence describes a situation that is currently happening. So, Simple Present Tense should be used.
> fix: use "is" instead of "were"

- docs/specs/meta-clients/web3wallet/sdk-api.md
Make it easier for Wallet developers to register their device token for the Echo Server to receive Push Notifications for both Auth request and Sign sessions 
We also need to update docs for Web3Wallet SDKs in:
> Add registerDeviceToken to Web3Wallet spec

- docs/specs/clients/chat/client-api.md
- Add invite events for `accepted` and `rejected`
- `accepted` should be used in favor of `chat_joined`, as it has been **removed**
> Add invite events

- docs/specs/clients/chat/chat-authentication.md
- docs/specs/clients/chat/invite-keys.md
- docs/specs/clients/push/push-authentication.md
- docs/specs/clients/push/push-proposal.md
- docs/specs/clients/push/rpc-methods.md
- docs/specs/clients/push/wallet-client-api.md
- docs/specs/servers/cast/cast-server-api.md
- docs/specs/servers/keys/identity-keys.md
- docs/specs/servers/keys/keys-server-api.md
- Extract Identity Keys from Chat API
- Update push proposal and rpc methods
- add address prove for Cast register
> Add identity keys to push

- docs/specs/clients/sign/data-structures.md
SessionSettle was missing `requiredNamespaces`, `optionalNamespaces`, and `sessionProperties` as per CAIP-25.
> Update SessionSettle to Match CAIP-25

- docs/specs/clients/core/pairing/rpc-methods.md
Problem:
The Pairing API specifies a `updateExpiry` method, but there is no way to communicate an updated expiration time to the paired app/wallet.
I propose the following:
1. Changing `updateExpiry` in the pairing to match session's `extend`.
2. Adding a new RPC method, as listed here, that defines the way to update the expiration of the pairing for both connected parties.
It's totally possible that you guys decided you didn't want to have the ability to extend pairings. If that's the case, then we can close this PR, document that fact somewhere, and move on.
> Add wc_pairingExtend

- docs/specs/clients/chat/client-api.md
`addContact` method was no longer necessary since we changed `Invite` structure used as parameter in `client.invite()` method. `Invite` structure always contains `inviteePublicKey` which is `publicKeyX` from [specs](https://docs.walletconnect.com/2.0/specs/clients/chat/chat-invite)
> docs: Removed addContact method

- docs/advanced/rpc-reference/near-rpc.md
- sidebars.js
- Added method names for NEAR that should be implemented by wallets.
- Added docs to the RPC Reference section.
The method names a wallet should implement to add support for NEAR + WalletConnect are based on the [Bridge Wallets](https://github.com/near/NEPs/blob/master/specs/Standards/Wallets/BridgeWallets.md) standard.
NEAR has already been added to the WalletConnect web-examples:
Github: https://github.com/WalletConnect/web-examples
Live: https://react-wallet.walletconnect.com/
The easiest way for dApps to add support for NEAR + WalletConnect is to use the `@near-wallet-selector/wallet-connect` package:
https://github.com/near/wallet-selector/tree/main/packages/wallet-connect which follows the Bridge Wallets standard for NEAR.
To test out the communication dApp -> wallet please follow …
> Create WalletConnect RPC Reference for NEAR

- docusaurus.config.js
Removed mention of v1.0 Getting Started from docs footer
Added links to [Web3Modal SDK](https://docs.walletconnect.com/2.0/web3modal/about) and [Web3Wallet SDK]((https://docs.walletconnect.com/2.0/web3wallet/about) for docs footer
| Before | After |
| ------------- | ------------- |
| <img width="203" alt="image" src="https://user-images.githubusercontent.com/26746725/230015126-c7e3bb53-019a-4731-b445-ac48e7b2cece.png"> | <img width="223" alt="image" src="https://user-images.githubusercontent.com/26746725/230015615-e8be61a9-8161-4819-8804-1d01571b759e.png"> |
Should we replace `Web3Modal SDK` with `Getting started for dApps` and `Web3Wallet SDK` with `Getting started for Wallets` or something along the lines of that?
> feat(docs-link): Removed v1.0 mention from footer, other changes

- docs/specs/clients/push/push-notification-types.md
* Spec references `in seconds` but concrete `lastModified` value shown is in milliseconds resolution
> fix(push): ensures `lastModified` example aligns with definition

- docs/reactnative/web3wallet/Installation.md
Had a duplicate npm install
Old version:
> chore: remove duplicate npm install

- docs/specs/clients/sync/client-api.md
- `set` should now return true if the existing value is different from the provided new value.  False otherwise.
- `delete` should now return true if there is an existing value associated with the provided key pre the deletion. False otherwise.
> Update sync client specs to prevent redundancy

- docs/specs/clients/sign/client-api.md
Update the function names in the spec to match Web3Wallet.
Goal:
Make libraries more maintainable by allowing them to use the same interfaces for both Sign and Web3Wallet APIs. You can run the same tests on both implementations, thus simplifying the number of tests that need to be written, and the maintenance necessary when changes must occur.
This also simplifies the end user's life: They can swap the Web3Wallet out with Sign, or the Sign API with the Web3Wallet, which means adding the Auth API is insanely easy if they already have the Sign API in place.
> Update Sign API to Match Web3Wallet

- docs/specs/clients/push/push-subscribe.md
- `Wallet subscribes to push topic` was right at the end, but the wallet already needs to be subscribed to the push topic to receive cast's response. 
- Moved it to `6.`
> fix(specs): update push subscribe flow ordering

- docs/specs/clients/push/data-structures.md
- Store descriptions for known notification types/scopes in order to meaningfully render options (e.g. enable/disable) for them in UIs.
- Based on: https://docs.walletconnect.com/2.0/specs/clients/push/push-notification-types#configuration
- Also: aligns typings to be TS-compliant
> fix(specs): add descriptions for push subscription scope

- docs/specs/clients/push/push-authentication.md
- docs/specs/clients/push/push-subscribe.md
- docs/specs/clients/push/rpc-methods.md
This PR changes how wc_pushSubscribe is handled to be consistent with Chat Invites where it also uses 3 topics:
1. Subscribe
2. Response
3. Push
> refactor push subscribe pattern

- docs/specs/clients/push/rpc-methods.md
- Explicitly mention which topic RPC methods are sent through
- Removes `replacesId` from wc_pushUpdate
> [Specs] update wc_pushUpdate

- docs/specs/clients/push/wallet-client-api.md
* The WalletClient requires a way to signal the result of `walletClient.update()` to the entity implementing the SDK (e.g. web3Inbox).
* We can  take a similar approach as with the `push_subscription` event, where `push_update` returns either:
* the updated subscription
* or an error
> fix(push): adds `push_update` event to WalletClient API

- docs/advanced/migration-from-v1.x/overview.md
As per screenshot, moved it higher for better visibility
Go to the migration page --> check the overview page.
> Move dapp/wallet hierachy higher in migration guide

- docs/specs/clients/push/rpc-methods.md
* The `scope` parameter provided for `propose(...)` in the top level API is a string array `string[]`
* In the actual `wc_pushPropose` it only indicates `string` which creates ambiguity around how/if the `scope` parameter needs to be processed before sending in a JSON-RPC request.
* Correcting to `string[]` to align with the original top level type
> fix(push-spec): corrects type for wc_pushPropose `scope` param

- sidebars.js
Move FAQs to the bottom to avoid two FAQs:
In favor of:
> Move FAQs to the bottom

- docs/specs/clients/core/sync/client-api.md
Small but powerful UX improvement. Currently, we always had to ask for a signature and then register. Now we could query the sdk if account did already register and then decide to ask for signature or move on
> feat: Adds a way to check if account was registered

- docs/specs/clients/push/wallet-client-api.md
Add params to `getActiveSubscriptions` to filter by account as right now, regardless of what wallet account queried the subscriptions, they'll all get the same result, which should not be the case
This can be seen in Web3inbox when logging into account A, subscribing, logging out, then logging into account B and querying active subs.
> Add account filtering for active subs

- docs/advanced/rpc-reference/tezos-rpc.md
The name was inconsistent in the docs and the implementations that exist. The proper name should be `operationHash`
> fix(tezos): fix property name

- docs/specs/clients/core/storage/storage-api.md
When building a UI for WalletConnect, we have to connect with multiple events in the Sign or Auth API to know when different internal values update.
This is not a straightforward approach.
I suggest adding the following events to the Storage API:
- onCreate, emitted when a new key is added
- onUpdate, emitted when a key that exists is updated in some way 
- onDelete, emitted when a key is removed
- onSync, emitted when data is persisted to disk
Some storage mechanisms in the Javascript repo already have events like these (JsonRpcHistory), and some have more (Expirer).
My goal is to make these events available for these storage endpoints: Pairings (Sign.Pairings), Sessions (Sign), Proposals (Sign), Cacao's (Auth, Completed Requests)
If the above storage endpoints exposing the 4 different …
> Storage Events

- docs/advanced/migration-from-v1.x/dapps/dapps.md
I think this is a mistake, there is no `showQrCode` key in the `EthereumProviderOptions`.
```
export interface EthereumProviderOptions {
projectId: string;
chains: number[];
optionalChains?: number[];
methods?: string[];
optionalMethods?: string[];
events?: string[];
optionalEvents?: string[];
rpcMap?: EthereumRpcMap;
metadata?: Metadata;
showQrModal: boolean;
qrModalOptions?: QrModalOptions;
disableProviderPing?: boolean;
relayUrl?: string;
storageOptions?: KeyValueStorageOptions;
}
```
Before:
```js
import { EthereumProvider } from '@walletconnect/ethereum-provider'
const provider = await EthereumProvider.init({
projectId: 'WALLETCONNECT_PROJECT_ID', // required
chains: [1], // required
showQrCode: true // requires @walletconnect/modal
})
```
After:
```js
import { EthereumProvider } …
```
> Change the key `showQrCode` to `showQrModal`.

- docs/advanced/migration-from-v1.x/dapps/dapps.md
Currently, both Web3Modal and WalletConnenct Modal are directed to: https://docs.walletconnect.com/2.0/web3modal/about
Updating this to take user to the install docs
> Fix: Link in Web3Modal migration

- docs/specs/clients/push/usage-of-sync-api.md
- docs/specs/clients/push/wallet-client-api.md
- Add `enableSync` method which enables sync by registering sync keys
- Document protocol changes  with sync in a separate doc, similar to chat
> Add initial docs for sync in push

- docs/advanced/multichain/overview.md
- We seem to getting a number of Explorer chain requests misunderstanding the actual effects of a chain being added to the Explorer as: `Explorer listing == wallet/dapp support`
- Our documentation seems to leave this open to interpretation at the moment
- This info admonition attempts to clarify that there is no direct cause-effect relationship between the two
> fix: adds callout to disambiguate Explorer vs protocol chain support

- docs/specs/servers/cast/cast-server-api.md
Moving to Bearer auth to match HTTP specs.
> cast: move to bearer auth

- docs/specs/clients/notify/notify-authentication.md
Currently every time the Wallet client subscribes, updates or deletes… it targets the dapp domain url as aud but this is contradicts the best practice for did-jwt which where both iss and aud should be DIDs
My proposal is that we always target the Dapp identity key and include the dapp domain url as app param
> [Specs] Notify API - Consistent DID-JWT Usage

- docs/web3wallet/about.mdx
While going through the `react-native` documentation, I noticed that the `@react-native-community/netinfo` dependency was missing. This PR aims to address this oversight and ensure that users have all the necessary information to set up their projects.
- Added `@react-native-community/netinfo` to the list of dependencies in the documentation.
https://github.com/WalletConnect/walletconnect-monorepo/blob/v2.0/packages/react-native-compat/package.json#L30
> Update React Native documentation to include missing @react-native-community/netinfo dependency

- docs/advanced/multichain/chain-list.md
as discussed on Slack with @glitch-txs  and [here](https://github.com/orgs/WalletConnect/discussions/3527).  i'm not particularly/picky if people want to change the wording (i.e. just go ahead and change it and merge it without waiting for my approval!). I just thought people should know that *in theory* the entire universe of valid CAIP-2s can be used with WC (they just need to be registered).
> add link to CASA namespaces docs from chain-list page

- docs/advanced/walletconnectmodal/about.mdx
- docs/advanced/walletconnectmodal/resources.mdx
Added links for Modal + Viem/Ethers/UProvider examples
Related with: https://github.com/WalletConnect/react-native-examples/pull/99
> Changed rn dapp example links

- docs/web3modal/react-native/about.mdx
Added extra step to detect installed wallets in w3m-rn
Solves:
React Native doesn't link native code unless is explicitly added in the package.json, so in order to detect installed wallets we need to add core package to the project. 
[Related issue](https://github.com/react-native-community/cli/issues/870)
> w3m: added extra step for installed wallets

- docs/advanced/walletconnectmodal/usage.mdx
Fixes docs type to match [`OpenOptions`](https://github.com/WalletConnect/modal/blob/95571fb4e96bd2a5c36214e657dc66aae0f1c8b4/packages/modal-core/src/controllers/ModalCtrl.ts#L10)
> fix: type of chains in OpenOptions

- docs/web3modal/nextjs/ethers/about/implementation.mdx
In the previous version of the current code example, there was a `<WagmiConfig />` component and `wagmiConfig` as a prop passed to the component. However, neither the `wagmiConfig` nor the `WagmiConfig` provided was mentioned above. I attempted to remove them, and it worked successfully for me.
As a relatively new user of Next.js, I am using version "next": "14.0.1" and incorporating the app router. To streamline my code, I've consolidated all my providers into `app/providers.tsx`. Additionally, I've placed the implementation code for `createWeb3Modal(...)` right before the actual `<CombineProvider />` component begins.
In the current patch, I've modified `Web3Connect.tsx` to have a simple div wrapper, allowing the injection of vanilla JavaScript code without the inclusion of actual …
> Remove WagmiConfig mentions in Next.js example using ethers

- docs/api/notify/usage.mdx
- docs/web3wallet/notify/installation.mdx
- docs/web3wallet/notify/usage.mdx
Web3Inbox React Native SDK is deprecated because it uses a web view and Web3Inbox communicators which we decided to rely on anymore.
This PR replaces references to the W3I RN SDK by Notify API docs and also provides guidance on how to handle push notifications on React Native.
> chore(remove-w3i-rn-sdk): remove references to W3I SDK

- README.md
- docusaurus.config.js
- package.json
- yarn.lock
Removed env file required for markprompt before
> fix: removed .env file

- docs/api/notify/usage.mdx
- docs/components/PlatformTabs.js
- docs/web3inbox/domain-setup.mdx
- docs/web3inbox/frontend-integration/api.mdx
- docs/web3inbox/frontend-integration/usage.mdx
- docs/web3inbox/sending-notifications.mdx
- docs/web3modal/upgrade.mdx
- docs/web3wallet/notify/usage.mdx
- Add more context and clarification around `domain` and `isLimited`
- Call `register()` when account changes
- Remove `const client = useWeb3InboxClient()` from hooks example as this is not intended to be used
- Add more missing `await`s and fix various function calls
- Remove "reactive" variables in-favor of `console.log()` for simplicity
- Add `watchSubscription()` to API
- Prefer `example.com` as example domains, rather than `mydomain.com` or the like, since it is an official example domain
- Prefer `javascript` over `js` for selecting language
- Use an actual example address `0x9AfEaC202C837df470b5A145e0EfD6a574B21029` instead of `...` or `0xFFF...`. This is same address from Notify Server API docs, and was randomly generated in the browser and private key not saved so this is …
> fix: Web3Inbox SDK fixes

- docs/cloud/explorer.md
- Renamed as Explorer API
- Removed unnecessary duplicate info about cloud submissions
- Added in Legacy API Deprecation info.
> Update Explorer API page with legacy endpoint info

- docs/advanced/migration-from-v1.x/wallets/wallet-checklist.md
This pull request removes the Auth API section from the migration guide in the web3 wallet integration section of the WalletConnect documentation.
fixes: #1232
> Removed Auth API from migration guide

- docs/web3inbox/sending-notifications.mdx
Loosen `/notify` rate limit after receiving developer feedback.
> chore: update limits

- docs/web3inbox/sending-notifications.mdx
Document the structure of the request body. E.g. we didn't include `notification_id` in the examples before.
> fix: document request body structure

- src/css/custom.css
> fix: markprompt dialog z-index

- docusaurus.config.js
- Update banner as per [copy req's](https://www.notion.so/walletconnect/Docs-banner-for-SDK-updated-ddf7dfb5e20c408fa7ddfb07959ab10a?pvs=4)
- Remove emojis 😦 
To go live at 14:00 GMT Dec 12
> feat: Web3Inbox SDK banner

- docs/advanced/migration-from-v1.x/dapps/dapp-checklist.md
- docs/advanced/migration-from-v1.x/wallets/wallet-checklist.md
- docs/advanced/multichain/overview.md
- docs/advanced/multichain/polkadot/namespaces-guide.md
- docs/advanced/multichain/polkadot/wallet-integration-guide.md
- docs/api/auth/dapp-usage.md
- docs/api/auth/wallet-usage.md
- docs/api/chat/resources.mdx
- docs/api/chat/usage.mdx
- docs/api/sign/dapp-usage.md
- docs/api/sign/wallet-usage.md
- docs/web3wallet/resources.mdx
- docs/web3wallet/wallet-usage.mdx
We want to move low level web examples under an advanced folder
https://github.com/WalletConnect/web-examples
> add advanced folder for web-examples link path

- docs/web3wallet/notify/introduction.mdx
> Chore: Move Sign API information to the top for Notify

- src/css/custom.css
> fix: updated lightmode text color in blockquotes

- docs/web3modal/nextjs/wagmi/about/implementation.mdx
Updated the Web3Modal NextJS docs to include ReactNode and Wagmi State imports.
> Add ReactNode and Wagmi State import to Web3Modal Docs.

- docs/web3wallet/notify/usage.mdx
This PR also removes `deleteNotification()` method for all sdks and renames `getMessageHistory` to `getNotificationHistory`
> feat: Kotlin Notify API

- docs/cloud/analytics.mdx
> fix(analytics): added distinction between relay and web3modal sessions

- docs/cloud/blockchain-api.md
This PR is syncing the Blockchain-API service limits to the limits from the Cloud app by adjusting limits to 6M requests per month in the docs.
> fix(cloud): syncing blockchain-api limits

- docs/web3modal/javascript/email/index.mdx
- docs/web3modal/nextjs/email/index.mdx
- docs/web3modal/react/email/index.mdx
- docs/web3modal/shared/email-alert.mdx
- docs/web3modal/vue/email/index.mdx
Dapps must be on allowlist in order to use emails. Added notification to be clear about it.
> chore: add allowlist requirement in email alert

- docs/getting-started.mdx
Changed "WalletConnect Explorer allows users to discover _and_ WalletConnect-enabled dapps and wallets." to "WalletConnect Explorer allows users to discover WalletConnect-enabled dapps and wallets." for better intelligibility.
> Remove unnecessary 'and'

- docs/web3modal/flutter/options.mdx
- docs/web3wallet/wallet-usage.mdx
Documentation associated with Sign Engine fixes https://github.com/WalletConnect/WalletConnectFlutterV2/pull/269
> [Flutter] Updated wallet documentation in regards of session approvals and requests

- docs/web3modal/v2/_partials/options/chains.mdx
* The CAIP-2 standard for Solana was fixed after-the-fact to contain the correct genesis hashes for each chain: https://github.com/ChainAgnostic/namespaces/blob/main/solana%2Fcaip2.md#test-cases
* Our documentation and sample code references need to be adjusted to the canonical hashes/chainIds.
> fix: update Solana CAIP-2 chainId reference

- docs/advanced/push-server.md
- docs/web3wallet/push-notifications.mdx
In regards to [this conversation](https://github.com/WalletConnect/walletconnect-monorepo/issues/4465#) we don't actually tell the developer following the Web3Wallet guide how to setup Push Server. Adding the relevant links for that, as well as streamlining the Push Server docs.
> fix: improve Push Server docs

- docs/appkit/javascript/core/siwe.mdx
- docs/appkit/next/core/siwe.mdx
- docs/appkit/react/core/siwe.mdx
- docs/appkit/shared/siwe/code.mdx
- docs/appkit/shared/siwe/parameters.mdx
- docs/appkit/vue/core/siwe.mdx
Added groupId to SIWE tabs so when the user press "One-Click Auth" or "Legacy" it changes in all tabs
Before:
https://github.com/WalletConnect/walletconnect-docs/assets/25931366/d076bb91-e1d3-451a-a399-f007093933ec
After:
https://github.com/WalletConnect/walletconnect-docs/assets/25931366/15c76b67-9e7a-450f-baa0-73d9a3198b27
> Fix: Added groupId to siwe tabs

- docs/walletkit/react-native/installation.mdx
Added missing package installation for Expo projects that want to use Web3Wallet React Native
related: https://github.com/WalletConnect/walletconnect-monorepo/issues/4586
> chore: added extra step for RN w3w expo

- docs/appkit/vue/wagmi/about/implementation.mdx
Title: Fix usage of composables in web3modal
Description:
I encountered an issue when using the composables in the web3modal library. Specifically, I was getting the following error message:
Please call "createWeb3Modal" before using "useWeb3Modal"
To address this, I made a fix that ensures createWeb3Modal is called before useWeb3Modal is used. This should resolve the initialization issue and make the composables work as expected.
I was able to fix the problem by adding the /vue to the end of the path of the following import. This is what it said to do in the documentation:
import { createWeb3Modal, defaultWagmiConfig } from "@web3modal/wagmi
I changed it to:
import { createWeb3Modal, defaultWagmiConfig } from "@web3modal/wagmi/vue"
Related Issue/Comment:
The clue to solving this problem …
> added: /vue to the path for createWeb3Modal.

- docs/appkit/react-native/wagmi/about/implementation.mdx
Replacing the `chains` parameter with the `defaultChain` during the Web3Modal initialisation.
The chains parameter does not exist anymore.
> Replacing example containing non-existent parameter

- docs/advanced/security/content-security-policy.md
- Noticed these weren't accounted for initially but should be whitelisted for usage of https://docs.walletconnect.com/appkit/features/notifications
> fix(csp): adds notify-relevant subdomains to `connect-src` recs

- docs/readme.mdx
- sidebars.js
- Remove WalletConnectModal from the sidebar and the main view
- Links to WalletConnectModal are still available but isolated
> Remove WalletConnectModal from docs.

- docs/advanced/walletconnectmodal/usage.mdx
- docs/api/core/pairing.mdx
- docs/api/core/relay.mdx
- docs/api/notify/usage.mdx
- docs/api/sign/dapp-usage.md
- docs/api/sign/wallet-usage.md
- docs/appkit/android/core/usage.mdx
- docs/walletkit/android/mobile-linking.mdx
- docs/walletkit/android/notifications/notify/usage.mdx
- docs/walletkit/android/usage.mdx
This PR introduces a simplified CoreClient initialize method where developers would have to pass only projectId without the Relay URL. The Relay URL is built internally.
For backward compatibility, the old method is not removed.
> kotlin: new CoreClient initialize method

- docs/appkit/react-native/core/installation.mdx
- docs/appkit/react-native/ethers/about/installation.mdx
- docs/appkit/react-native/ethers/email.mdx
- docs/appkit/react-native/ethers5/about/installation.mdx
- docs/appkit/react-native/onboarding/email.mdx
- docs/appkit/react-native/wagmi/about/installation.mdx
- docs/appkit/react-native/wagmi/email.mdx
- docs/walletkit/react-native/installation.mdx
- docs/walletkit/react-native/notifications/notify/installation.mdx
- docs/walletkit/react-native/notifications/notify/usage.mdx
* Added extra step for universal wallets to config Cloud allowed mobile apps
* Removed npm2yarn plugin from react native docs
> chore: added cloud note for react native universal wallets

- docs/advanced/security/content-security-policy.md
This reverts commit 4a73cc1056265b98c910401d011877dd9cfbca01.
This change was not necessary as Verify V2 was incompatible with best practice CSPs. Verify V3 takes a new approach which uses the same CSP values as before.
> Revert "fix: update CSP"

- docs/appkit/features/socials.mdx
Add only the EVM-supported chain for social logins.
Preview: https://walletconnect-docs-git-feat-add-social-lo-831ddf-walletconnect1.vercel.app/appkit/features/socials
> feat: Add EVM supported chains for social login
